version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint:
        patterns:
          - "esbuild*"
      esbuild:
        patterns:
          - "esbuild*"
      stylelint:
        patterns:
          - "stylelint*"
      patternfly:
        patterns:
          - "@patternfly*"
