version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "esbuild"
          - "eslint"
          - "stylelint"
      dependencies:
        patterns:
          - "@patternfly"
